version: '3.8'

services:

  nginx:
    image: nginx:latest
    container_name: cicd-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - jenkins-net
    volumes:
      - ${NGINX_CONF}:/etc/nginx/conf.d/default.conf
      - ${NGINX_SSL_CERTS}:/etc/ssl
      - ${NGINX_LOGS}:/var/log/nginx

  jenkins:
    image: jenkins/jenkins:lts
    container_name: cicd-jenkins
    restart: unless-stopped
    privileged: true
    user: root
    ports:
      - "50000:50000"
    expose:
      - "8080"
    networks:
      jenkins-net:
        aliases:
          - jenkins-net
    volumes:
      - ${JENKINS_DATA}:/var/jenkins_home
      - ${HOST_DOCKER_SOCK}:/var/run/docker.sock

volumes:
  jenkins-data:

networks:
  jenkins-net: