version: '3.8'

services:

#  nginx:
#    image: nginx:latest
#    container_name: cicd-nginx
#    restart: unless-stopped
#    ports:
#      - "80:80"
#      - "443:443"
#    networks:
#      - jenkins-net
#    volumes:
#      - ${JENKINS_DATA}:/var/jenkins_home
#      - ${NGINX_CONF}:/etc/nginx/conf.d/default.conf
#      - ${NGINX_SSL_CERTS}:/etc/ssl
#      - ${NGINX_LOGS}:/var/log/nginx

  jenkins-haproxy:
    image: haproxy:latest
    container_name: cicd-haproxy
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
    networks:
      - jenkins-net
    volumes:
      - ${HAPROXY_SSL_CERTS}:/etc/ssl/certs                              # full-chain certificate and key file
      - ${HAPROXY_CONF}:/usr/local/etc/haproxy/haproxy.cfg:ro            # haproxy.cfg configuration file
    depends_on:
      - jenkins

  jenkins:
    image: jenkins/jenkins:lts
    container_name: cicd-jenkins
    restart: unless-stopped
    privileged: true
    user: root
    ports:
      - "50000:50000"
    expose:
      - "8080"
    networks:
      - jenkins-net
    volumes:
      - ${JENKINS_DATA}:/var/jenkins_home
      - ${HOST_DOCKER_SOCK}:/var/run/docker.sock
    environment:
      - JENKINS_UID=${JENKINS_UID}
      - JENKINS_GID=${JENKINS_GID}
#      - JENKINS_JAVA_OPTS="-Dhudson.security.csrf.DefaultCrumbIssuer.EXCLUDE_SESSION_ID=true"
#      - JENKINS_JAVA_OPTS="-Dhudson.security.csrf.GlobalCrumbIssuerConfiguration.DISABLE_CSRF_PROTECTION=true"

volumes:
  jenkins-haproxy-ssl:
  jenkins-data:

networks:
  jenkins-net: