version: '3.8'

services:

  vault-server:
    image: hashicorp/vault:latest
    container_name: vault-server
    restart: unless-stopped
    ports:
      - "8200:8200"
    networks:
      default:
        # required for the FQDN to resolve locally on the host vm, so it can be bound by the tcp listener - for Vault TLS
        aliases:
          - vault-prd-01.int.leakespeake.com
    volumes:
      - ./config:/vault/config
      - ./file:/vault/file
      - ./logs:/vault/logs
      - ./policies:/vault/policies
      - ./ssl:/vault/ssl
    environment:
      - VAULT_ADDR=https://vault-prd-01.int.leakespeake.com:8200
      - VAULT_API_ADDR=https://vault-prd-01.int.leakespeake.com:8200
    command: vault server -config=/vault/config/
    # memory lock required to prevent swapping sensitive data to disk
    cap_add:
      - IPC_LOCK