version: '3'

services:
  phpipam-web:
    image: phpipam/phpipam-www:latest
    ports:
      - "80:80"
    environment:
      - TZ=Europe/London
      - IPAM_DATABASE_HOST=phpipam-mariadb
      - IPAM_DATABASE_PASS=${IPAM_DATABASE_PASS}
      - IPAM_DATABASE_WEBHOST=%
    restart: unless-stopped
    volumes:
      - phpipam-logo:/phpipam/css/images/logo
    depends_on:
      - phpipam-mariadb

  phpipam-cron:
    image: phpipam/phpipam-cron:latest
    environment:
      - TZ=Europe/London
      - IPAM_DATABASE_HOST=phpipam-mariadb
      - IPAM_DATABASE_PASS=${IPAM_DATABASE_PASS}
      - SCAN_INTERVAL=1h
    restart: unless-stopped
    depends_on:
      - phpipam-mariadb

  phpipam-mysql-backup:
    image: databack/mysql-backup:latest
    environment:
      - DB_SERVER=phpipam-mariadb
      - DB_PORT=3306
      - DB_USER=phpipam
      - DB_PASS=${IPAM_DATABASE_PASS}
      - DB_NAMES=phpipam
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=2100
      - DB_DUMP_TARGET=smb://ubuntu:REDACTED@NAS/backups /db
#     - DB_DUMP_CRON=0 0 * * 0
    user: "0"
    restart: unless-stopped
    volumes:
      - phpipam-db-backups:/db
    depends_on:
      - phpipam-mariadb

  phpipam-mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    restart: unless-stopped
    volumes:
      - phpipam-db-data:/var/lib/mysql

volumes:
  phpipam-db-data:
  phpipam-logo:
  phpipam-db-backups: